# -*- coding: ANSI_X3.4-1968 -*-
# generated by wxGlade 0.3.5.1 on Wed Jan 26 21:21:40 2005

import os
import wx

# begin wxGlade: dependencies
# end wxGlade

ID_MINNUM     = 100
ID_LIST       = 101
ID_ADD        = 103
ID_DELETE     = 104
ID_OK         = 105
ID_MAXNUM     = 110

class frmPaths(wx.Dialog):
    
    def __init__(self, *args, **kwds):

        for i in range(ID_MINNUM, ID_MAXNUM):
            wx.RegisterId(i)
            
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.SYSTEM_MENU | wx.CLOSE_BOX
        wx.Dialog.__init__(self, *args, **kwds)

        self.lblList = wx.StaticText(self, -1, "This library is bound to the following paths:")
        self.lstPaths = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE)
        self.cmdAdd = wx.Button(self, ID_ADD, "Add")
        self.cmdDelete = wx.Button(self, ID_DELETE, "Delete")
        self.cmdOK = wx.Button(self, ID_OK, "&OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        wx.EVT_BUTTON(self, ID_OK,         self.OnOK)
        wx.EVT_BUTTON(self, ID_ADD,        self.OnAdd)
        wx.EVT_BUTTON(self, ID_DELETE,     self.OnDelete)

        self.paths = []

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Library Root Paths")
        self.lstPaths.SetSize((300, 100))
        self.cmdOK.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizForm = wx.BoxSizer(wx.VERTICAL)
        sizButtons = wx.BoxSizer(wx.HORIZONTAL)
        sizForm.Add(self.lblList, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizForm.Add(self.lstPaths, 0, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 5)
        sizButtons.Add(self.cmdAdd, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizButtons.Add(self.cmdDelete, 0, wx.ALL|wx.FIXED_MINSIZE, 5)
        sizButtons.Add(self.cmdOK, 0, wx.ALL|wx.ALIGN_RIGHT|wx.FIXED_MINSIZE, 5)
        sizForm.Add(sizButtons, 1, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizForm)
        sizForm.Fit(self)
        sizForm.SetSizeHints(self)
        self.Layout()
        # end wxGlade


    def OnOK(self, e):
        """goodbye cruel world"""
        self.Destroy()

    def OnAdd(self, e):
        d = wx.DirDialog(self, "Choose FLAC storage root path", "~")
        if d.ShowModal() == wx.ID_OK:
            p = d.GetPath()
            if os.path.isdir(p):
                self.paths.append(p)
                self.displayPaths()
        d.Destroy()
        return
            
    def OnDelete(self, e):
        i = self.lstPaths.GetSelections()[0]
        del self.paths[i]
        self.displayPaths()

    def displayPaths(self):
        self.lstPaths.Set(self.paths)

# end of class MyFrame


